#pragma once

#include <vx_utils/casts.h>

#define VX_COMPONENT_EXPORT_IMPLICIT(_TYPE, _NAME) VX_IMPLICIT_CAST(_TYPE, _NAME)
#define VX_COMPONENT_EXPORT_EXPLICIT(_TYPE, _NAME) VX_EXPLICIT_CAST(_TYPE, _NAME)
#define VX_COMPONENT_EXPORT(_TYPE, _NAME) VX_COMPONENT_EXPORT_IMPLICIT(_TYPE, _NAME)