#
# Copyright 2011-2022 Branimir Karadzic. All rights reserved.
# License: https://github.com/bkaradzic/bgfx/blob/master/LICENSE
#

BGFX_DIR=../../../subprojects/bgfx/bgfx
RUNTIME_DIR=.
BUILD_DIR=./.build

include $(BGFX_DIR)/scripts/shader.mk