package vx_lib_gfx

Gfx_Handle :: u64

INVALID_HANDLE :: 0

COMMON_MODEL_UNIFORM_LOCATION :: 0
COMMON_VIEW_UNIFORM_LOCATION :: 1
COMMON_PROJ_UNIFORM_LOCATION :: 2

SKYBOX_VIEW_UNIFORM_LOCATION :: 0
SKYBOX_PROJ_UNIFORM_LOCATION :: 1
SKYBOX_CUBEMAP_UNIFORM_LOCATION :: 2

IMMEDIATE_VIEW_UNIFORM_LOCATION :: 0
IMMEDIATE_PROJ_UNIFORM_LOCATION :: 1
IMMEDIATE_TEXTURE_UNIFORM_LOCATION :: 2
